<?php

/**
 * ProcessWire 'TextformatterAbbreviation' module
 *
 * Replace all abbreviations found
 *
 * ProcessWire 2.x
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class TextformatterAbbreviation extends Textformatter {

	/**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 *
	 * @return array
	 *
	 */
	public static function getModuleInfo() {

		return array(

			'title' => 'Textformatter Abbreviation',
			'version' => 001,
			'summary' => 'Find all used abbreviations and mark with the right title',
			'href' => 'http://www.zenmotion.de',
			'singular' => true,
			'autoload' => true,
			'icon' => 'smile-o',
			'requires'    => 'Abbreviate',
			);
	}

	public function format(&$str) {

		require_once("abbreviate.php");
		$str = abbreviate(trim($str));
	}
}
