<?php

/**
 * ProcessWire 'TextformatterAbbreviation' module
 *
 * Replace all abbreviations found
 *
 * ProcessWire 2.x
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class TextformatterAbbreviation extends Textformatter {

	/**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 *
	 * @return array
	 *
	 */
	public static function getModuleInfo() {

		return array(

			// The module'ss title, typically a little more descriptive than the class name
			'title' => 'Textformatter Abbreviation',

			// version: major, minor, revision, i.e. 100 = 1.0.0
			'version' => 001,

			// summary is brief description of what this module is
			'summary' => 'Find all used abbreviations and mark with the right title',

			// Optional URL to more information about the module
			'href' => 'http://www.zenmotion.de',

			// singular=true: indicates that only one instance of the module is allowed.
			// This is usually what you want for modules that attach hooks.
			'singular' => true,

			// autoload=true: indicates the module should be started with ProcessWire.
			// This is necessary for any modules that attach runtime hooks, otherwise those
			// hooks won't get attached unless some other code calls the module on it's own.
			// Note that autoload modules are almost always also 'singular' (seen above).
			'autoload' => true,

			// Optional font-awesome icon name, minus the 'fa-' part
			'icon' => 'smile-o',
			);
	}

	public function format(&$str) {

		require_once("abbreviate.php");
		$str = abbreviate(trim($str));
	}
}
